name: Project CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run:  make -C src/tools

    # - name: test
    #   run:  src/libopenpmd examples/M/PAT1_P.M2

    - uses: actions/upload-artifact@v2
      with:
        name: pmd_instrip
        path: src/tools/pmd_instrip.exe

