name: Project CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  normal:
    strategy:
      matrix:
        config:
        - { name: 'Windows', os: windows-latest }
        - { name: 'macOS', os: macos-latest }
        - { name: 'Ubuntu', os: ubuntu-latest }
      fail-fast: false

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run:  cmake -B ${PWD}/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${PWD}/install

    - name: Build
      run:  cmake --build ${PWD}/build --parallel 2

    - name: Install
      run: cmake --install ${PWD}/build

    - name: Test
      run: |
        export PATH=${PWD}/install/bin:${PATH}
        if [ '${{ matrix.config.name }}' == 'Windows' ]; then
          function print_hash() {
            CertUtil -hashfile "$1"
          }
        elif [ '${{ matrix.config.name }}' == 'macOS' ]; then
          function print_hash() {
            shasum -a 256 "$1"
          }
        else
          function print_hash() {
            sha256sum "$1"
          }
        fi
        export -f print_hash

        mkdir test
        cd test

        loadtest ../examples/P86/RC1.P86
        mv TEST_MEM.P86 LOADTEST_MEM.P86
        mv TEST_FIL.P86 LOADTEST_FIL.P86

        p86extract LOADTEST_MEM.P86
        p86create TEST.*.RAW
        mv TEST.P86 P86CREATE.P86

        print_hash ../examples/P86/RC1.P86
        print_hash LOADTEST_MEM.P86
        print_hash LOADTEST_FIL.P86
        print_hash P86CREATE.P86
