name: Project CI

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run:  cmake -B $PWD/build

    - name: Build
      run:  cmake --build $PWD/build

    - name: Test
      run: |
        cd $PWD/build

        ./tools/loadtest
        mv test.P86 LOADTEST.P86

        ./tools/p86extract LOADTEST.P86
        ./tools/p86create TEST.*.RAW
        mv TEST.P86 P86CREATE.P86

        CertUtil -hashfile LOADTEST.P86 MD5
        CertUtil -hashfile P86CREATE.P86 MD5
